---
title: "Untitled"
output: html_document
date: '2024-07-18'
---

# Prerequisite

```{r package, warning=FALSE, echo=TRUE}
set.seed(2024)
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(tidyr) 
  library(here)
  library(ggplot2)
  library(metafor)
  library(cowplot)
  library(patchwork)
  library(RColorBrewer)
  library(viridis)
  library(ggrepel)}
  )

```

# First example

## Data

```{r}
# load example data
load(here("data","moller12.rda"))
# make a copy
dat <- moller12
```

## Fit a RE model
```{r}
# compute effect size
dat <- escalc(measure="OR", ai = r1, n1i = n1, ci = r2, n2i = n2, data = dat)

res <- rma(yi,vi, data = dat, method = 'REML', control = list(stepadj = 0.5, maxiter = 1000)) # https://github.com/cran/metafor/blob/master/R/influence.rma.uni.r
# all measures at one go
inf <- influence(res)$inf %>% as.data.frame()
inf$study.name <- as.character(dat$study.name) 
inf$id <- 1:nrow(inf)
```

## Visualization

https://github.com/cxli233/FriendsDontLetFriends#1-friends-dont-let-friends-make-bar-plots-for-means-separation

```{r}
# check for NA values and remove them if necessary
inf <- inf %>%
  filter(!is.na(weight) & !is.na(rstudent) & !is.na(dffits) & !is.na(cook.d) & !is.na(study.name))

inf <- inf %>%
  mutate(cov_status = ifelse(cov.r >= 1, "Increased", "Decreased"))

p1 <- inf %>% 
 ggplot(aes(x = weight, y = rstudent)) +
  geom_hline(yintercept = 1.96, size = 0.5, linetype = "dashed", color = "red") +
  geom_hline(yintercept = -1.96, size = 0.5, linetype = "dashed", color = "red") +
  geom_point(aes(fill = cook.d, size = dffits), shape = 21) +
  scale_fill_gradientn(breaks = c(0, 0.2, 0.4, 0.6), labels = c(0, 0.2, 0.4, 0.6), colors = rev(brewer.pal(11, "RdBu"))) +
  scale_y_continuous(limits = c(-3, 5)) +
  labs(caption = "", x = "Weight", y = "Externally standardized residuals", fill = "Cook distance", size = "Coefficient difference") +
  theme_bw() +
  theme(
    axis.text = element_text(size = 16, color = "black"), 
    axis.title = element_text(size = 18, color = "black"), 
    legend.position = "right",
    legend.title=element_text(size = 16), 
    legend.text=element_text(size = 16)
  ) + 
   geom_text(aes(label = id), size = 6, hjust = 0.5, vjust = 2)  
   #geom_text(aes(x = 6.54233 + 0.6, y = 4.841277, size = 4, label = "MASS III 2009"))

inf %>% 
  ggplot(aes(x = id, y = tau2.del)) +
  geom_segment(aes(x = id, xend = id), 
               yend = 0, size = 1.2, alpha = 0.8, color = "grey60") +
  geom_point(shape = 21, aes(fill = tau2.del, size = tau2.del)) +
  scale_fill_gradientn(colors = viridis(n = 10)) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Study ID", y = expression(paste("Estimated between-study variance ", tau^2)), fill = expression(tau^2)) +
  theme_bw() +
  theme(
    axis.text = element_text(size = 16, color = "black"), 
    axis.title = element_text(size = 18, color = "black"), 
    legend.position = "none",
    legend.title = element_text(size = 16), 
    legend.text = element_text(size = 16)
  )


```


# Second example

## Data

```{r}
# load example data
load(here("data","lahart18.rda"))
# make a copy
dat2 <- lahart18
```

## Fit a RE model
```{r}
res2 <- rma(y, vi = s2, data = dat2, method = 'REML', test = "knha", control = list(stepadj = 0.5, maxiter = 1000))
# all measures at one go
inf2 <- influence(res2)$inf %>% as.data.frame()
inf2$study.name <- as.character(dat2$study.name) 
inf2$id <- 1:nrow(inf2)
```

## Visualization

```{r}
# check for NA values and remove them if necessary
inf2 <- inf2 %>%
  filter(!is.na(weight) & !is.na(rstudent) & !is.na(dffits) & !is.na(cook.d) & !is.na(study.name))

inf2 <- inf2 %>%
  mutate(cov.r2 = sqrt(1 / cov.r))


p2 <- inf2 %>% 
 ggplot(aes(x = hat, y = rstudent)) +
  geom_hline(yintercept = 1.96, size = 0.5, linetype = "dashed", color = "red") +
  geom_hline(yintercept = -1.96, size = 0.5, linetype = "dashed", color = "red") +
  geom_point(aes(fill = QE.del, size = cov.r2), shape = 21) +
  scale_fill_gradientn(breaks = c(5,  10, 15), colors = viridis(n = 10)) +
  scale_y_continuous(limits = c(-5, 2)) +
  labs(caption = "", x = "Leverage", y = "Externally standardized residuals", fill = "Cochrane's Q", size = "Error difference") +
  theme_bw() +
  theme(
    axis.text = element_text(size = 16, color = "black"), 
    axis.title = element_text(size = 18, color = "black"),
    legend.position = "right",
    legend.title = element_text(size = 16), 
    legend.text = element_text(size = 16)
  ) + 
   geom_text(aes(label = id), size = 6, hjust = 0.5, vjust = 2)
   #geom_text(aes(x = 0.1247957 + 0.01, y = -4.341413, size = 4, label = "Schmitz 2005"))

```

# Assembly

```{r}
png(filename = "fig.png", width = 12, height = 12, units = "in", type = "windows", res = 800)
p1 + p2 + plot_layout(nrow = 2, ncol = 1) +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 16))
dev.off() 

```


# Third example

## Data

```{r}
dat3 <- escalc(measure = "RR", ai = tpos, bi = tneg, ci = cpos, di = cneg, data = dat.bcg)
```


## Fit a RE model

```{r}


res3 <- rma(yi, vi, mods = ~ ablat + year, method = 'REML', data = dat3, control = list(stepadj = 0.5, maxiter = 1000))
# all measures at one go
inf3 <- influence(res3)$inf %>% as.data.frame()
inf3$study.name <- as.character(dat3$author) 
inf3$id <- 1:nrow(inf3)
```

## Visualization

```{r}
p3 <- inf3 %>% 
 ggplot(aes(x = weight, y = rstudent)) +
  geom_hline(yintercept = 1.96, size = 0.5, linetype = "dashed", color = "red") +
  geom_hline(yintercept = -1.96, size = 0.5, linetype = "dashed", color = "red") +
  geom_point(aes(size = cook.d, fill = dffits), shape = 21) +
  scale_fill_gradientn(breaks = c(-3, -2, -1, 0, 1), labels = c(-3, -2, -1, 0, 1), colors = rev(brewer.pal(11, "RdBu"))) +
  scale_y_continuous(limits = c(-3, 3)) +
  labs(caption = "", x = "Weight", y = "Externally standardized residuals", fill = "Coefficient difference", size = "Cook distance") +
  theme_bw() +
  theme(
    axis.text = element_text(size = 16, color = "black"), 
    axis.title = element_text(size = 18, color = "black"), 
    legend.position = "right",
    legend.title=element_text(size = 16), 
    legend.text=element_text(size = 16)
  ) + 
   geom_text(aes(label = id), size = 6, hjust = 0.5, vjust = 2)  


```


# Estimator

```{r}

res <- rma(yi,vi, data = dat, method = 'REML', control = list(stepadj = 0.5, maxiter = 1000))
# using different estimators
res.HS <- rma(yi, vi, data = dat, method = "HS")
res.HE <- rma(yi, vi, data = dat, method = "HE")
res.DL <- rma(yi, vi, data = dat, method = "DL")
res.ML <- rma(yi, vi, data = dat, method = "ML")
res.REML <- rma(yi, vi, data = dat, method = "REML")
res.EB <- rma(yi, vi, data = dat, method = "EB")
res.SJ <- rma(yi, vi, data = dat, method = "SJ")
# extract estimates
res.list <- list(res.HS, res.HE, res.DL, res.ML, res.REML, res.EB, res.SJ)

df.tau2 <- data.frame(method = sapply(res.list, function(x) x$method),
           tau2 = sapply(res.list, function(x) round(x$tau2,3)),
           I2 = sapply(res.list, function(x) round(x$I2,0)))
```

